reportPath = C:\\Automation\\Regression_Report
successimagespath = \\target\\SuccessScreenshots
UTILS_FILE_PATH = src/main/resources/webConfig/utils.properties
failureimagespath = \\target\\FailureScreenshots